version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: god_it
      POSTGRES_PASSWORD: 5344166
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
